Unit NFe.Scripts;

Interface

Uses
   System.SysUtils, System.Math, {MZ.Biblioteca,} FireDAC.Comp.Client;

Type
   TTipoCobranca = (tcCobranca, tcDuplicata, tcPagamento, tcNone);

   TNFeScript = Class
      Class Function ScriptCabecalho(Const IdNFe: Integer): String; // B
      Class Function ScriptEmitente(Const IdNFe: Integer): String; // C
      Class Function ScriptDestinatatrio(Const IdNFe: Integer): String; // E
      Class Function ScriptIdentificacao(Const IdNFe: Integer): String; // B, C, E
      Class Function ScriptProdutosEImpostos(Const IdNFe: Integer): String; // H, I, LA, N, NA, O, Q, S
      Class Function ScriptReferenciadas(Const IdNFe: Integer): String; // B02, VC
      Class Function ScriptRetiradas(Const IdNFe: Integer): String; // F
      Class Function ScriptEntregas(Const IdNFe: Integer): String; // G
      Class Function ScriptAutorizacao(Const IdNFe: Integer): String; // GA
      Class Function ScriptCobranca(Const IdNFe: Integer; Const TipoCobranca: TTipoCobranca): String; // Y, Y07, YA
      Class Function ScriptTransportador(Const IdNFe: Integer): String; // X, X22,X26, X33
      Class Function ScriptTransporte(Const IdNFe: Integer): String;
      Class Function ScriptReboque(Const IdNFe: Integer): String;
      Class Function ScriptVolumes(Const IdNFe: Integer): String;
      Class Function ScriptLacres(Const IdNFe, Volume: Integer): String;
      Class Function ScriptInfoAdicional(Const IdNFe: Integer): String;
      Class Function ScriptInfoContrib(Const IdNFe: Integer): String;
      Class Function ScriptInfoFisco(Const IdNFe: Integer): String;

      Class Function ScriptTotais(Const IdNFe: Integer): String; // W
      Class Function ScriptTotaisISIBSCBS(Const IdNFe: Integer): String; // W03

      // IMPLEMENTAR
      Class Function ScriptISIBSCBS(Const IdNFe: Integer): String;
      { IMPLEMENTAR } Class Function ScriptPagamentoAntecipado(Const IdNFe: Integer): String;
      { IMPLEMENTAR } Class Function ScriptCompraGov(Const IdNFe: Integer): String;
   Private
   End;

Implementation

Class Function TNFeScript.ScriptCabecalho(Const IdNFe: Integer): String;
Begin
   // BLOCOS B-IDENTIFICAÇÃO
   Result := Format(
      'SELECT ID_NFE, ID_EMPRESA, NNF_B08, CUF_B02, CNF_B03, NATOP_B04, CODIGO_NATOP_B04, MOD_B06, SERIE_B07, DHEMI_B09, ' +
      'DHSAIENT_B10, TPNF_B11, IDDEST_B11A, CMUNFG_B12, TPIMP_B21, TPEMIS_B22, CDV_B23, TPAMB_B24, FINNFE_B25, ' +
      'INDFINAL_B25A, INDPRES_B25B, INDINTERMED_B25C, PROCEMI_B26, VERPROC_B27, DHCONT_B28, XJUST_B29, DPREVENTREGA_B10A ' +
      'FROM NFE ' +
      'WHERE ID_NFE = %d', [IdNFe]);
   // INDPAG_B05
End;

Class Function TNFeScript.ScriptEmitente(Const IdNFe: Integer): String;
Begin
   // BLOCO C - EMITENTE
   Result := Format(
      'SELECT ID_NFE, ID_EMPRESA, CNPJ_C02, CPF_C02A, XNOME_C03, XFANT_C04, ' +
      'XLGR_C06, NRO_C07, XCPL_C08, XBAIRRO_C09, CMUN_C10, XMUN_C11, UF_C12, CEP_C13, CPAIS_C14, XPAIS_C15, ' +
      'FONE_C16, IE_C17, IEST_C18, IM_C19, CNAE_C20, CRT_C21, ISUFEMIT_C22 ' +
      'FROM NFE ' +
      'WHERE ID_NFE = %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptDestinatatrio(Const IdNFe: Integer): String;
Begin
   // BLOCO E - DESTINATÁRIO
   Result := Format(
      'SELECT ID_NFE, ID_EMPRESA, ' +
      'CNPJ_E02, CPF_E03, IDESTRANGEIRO_E03A, XNOME_E04, XLGR_E06, NRO_E07, XCPL_E08, XBAIRRO_E09, CMUN_E10, XMUN_E11, UF_E12, ' +
      'CEP_E13, CPAIS_E14, XPAIS_E15, FONE_E16, INDIEDEST_E16A, IE_E17, ISUF_E18, IM_E18A, EMAIL_E19 ' +
      'FROM NFE ' +
      'WHERE ID_NFE = %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptAutorizacao(Const IdNFe: Integer): String;
Begin
   // BLOCO GA - AUTORIZAÇÃO
   Result := Format(
      'SELECT ID_NFE, ID_AUT, CNPJ_GA02, CPF_GA03 ' +
      'FROM NFE_AUTORIZA_XML ' +
      'WHERE ID_NFE = %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptEntregas(Const IdNFe: Integer): String;
Begin
   // BLOCO G - ENTREGA
   Result := Format(
      'SELECT ID_NFE, CNPJ_G02, CPF_G02A, XLGR_G03, NRO_G04, XCPL_G05, XBAIRRO_G06, CMUN_G07, XMUN_G08, UF_G09 ' +
      'FROM NFE_LOCAL_ENTREGA ' +
      'WHERE ID_NFE = %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptCobranca(Const IdNFe: Integer; Const TipoCobranca: TTipoCobranca): String;
Begin
   Result := '';
   Case TipoCobranca Of
      tcCobranca:
         // '-- SQL PARA O BLOCO Y -COBRANCA ' +
         Result := Format(
            'SELECT ID_NFE, NFAT_Y03, VORIG_Y04, VDESC_Y05, VLIQ_Y06 ' +
            'FROM NFE_COBRANCA ' +
            'WHERE ID_NFE = %d', [IdNFe]);

      tcDuplicata:
         // '-- SQL PARA O BLOCO Y07 - DUPLICATAS ' +
         Result := Format(
            'SELECT ID_NFE, Ndup_Y08, Dvenc_Y09, Vdup_Y10 ' +
            'FROM Nfe_Duplicatas ' +
            'WHERE ID_NFE = %d', [IdNFe]);

      tcPagamento:
         // '-- SQL PARA O BLOCO YA - MEIOS DE PAGAMENTO ' +
         Result := Format(
            'SELECT ID_NFE, TPAG_YA02, XPAG_YA02A, VPAG_YA03, INDPAG_YA01B, TPINTEGRA_YA04A, CNPJ_YA05, TBAND_YA06, CAUT_YA07, VTROCO_YA08 ' +
            'FROM NFE_PAGAMENTO ' +
            'WHERE ID_NFE = %d', [IdNFe]);
   End;
End;

Class Function TNFeScript.ScriptIdentificacao(Const IdNFe: Integer): String;
Begin
   // '-- SQL para o blocos B-Identificação, C-Emitente e E-Destinatário ' +
   Result := Format(
      'DPREVENTREGA_B10A, CMUNFGIBS_B12A, TPNFDEBITO_B25_1, TPNFCREDITO_B25_2, TPENTEGOV_B32, PREDUTOR_B33, TPOPERGOV_B34, ' +
      'INDINTERMED_B25C, CINDOP_B25D, TPENTEGOV_BB02, PREDUTOR_BB03, TPOPERGOV_BB04, ' +

      'VBC_W03, VICMS_W04, VICMSDESON_W04A, VBCST_W05, VST_W06, ' +
      'VPROD_W07, VFRETE_W08, VSEG_W09, VDESC_W10, VII_W11, VIPI_W12, VPIS_W13, VCOFINS_W14, VOUTRO_W15, VNF_W16, ' +
      'VTOTTRIB_W16A, MODFRETE_X02, VAGAO_X25A, BALSA_X25B, INFADFISCO_Z02, INFCPL_Z03, EMP_I_COD, UFEMBARQ_ZA02, ' +
      'XLOCEMBARQ_ZA03, XLOCDESPACHO_ZA04, XNEMP_ZB02, XPED_ZB03, XCONT_ZB04, CHAVE_S_NUM, STATUS_NFE, PROTOCOLO_ENV, ' +
      'STATUS_CORR, SEQUENCIA_CORR, DATA_CAN, PROTOCOLO_CAN, MOTIVO_CAN, CLI_I_COD, CLI_I_EMP, FOR_I_COD, ORIGEM_TIPO, ' +
      'ORIGEM_CODIGO, VFCPUFDEST_W04C, VICMSUFDEST_W04E, VICMSUFREMET_W04G, XML, QRCODE_ZX02, VFCP_W04H, ' +
      'VFCPST_W06A, VFCPSTRET_W06B, VIPIDEVOL_W12A, STATUS_NSEG, LINK_NOTASEGURA, XML_CAN, CPR_I_COD, ' +
      'QBCMONO_W06B1, VICMSMONO_W06C, QBCMONORETEN_W06C1, VICMSMONORETEN_W06D, QBCMONORET_W06D1, VICMSMONORET_W06E, ' +

      (* MOVIDO PARA ScriptTotaisISIBSCBS
        'VIS_W33, VBCIBSCBS_W35, VDIF_W38, VDEVTRIB_W39, VIBSUF_W41, VDIF_W43, VDEVTRIB_W44, VIBSMUN_W46, ' +
        'VIBS_W47, VCREDPRES_W48, VCREDPRESCONDSUS_W49, VDIF_W53, VDEVTRIB_W54, VCBS_W56, VCREDPRES_W56A, VIBSMONO_W58, ' +
        'VCBSMONO_W59, VIBSMONORETEN_W59A, VCBSMONORETEN_W59B, VIBSMONORET_W59C, VCBSMONORET_W59D, VIBSESTCRED_W59F, ' +
        'VCBSESTCRED_W59G, VNFTOT_W60, ' +
      *)

      'EXPORTA_SPED, ERRO_NSEG ' +
      'FROM NFE ' +
      'WHERE ID_NFE = %d', [IdNFe]);

   {
     Result := Format(
     '/*EMITENTE*/'+
     'SELECT ID_NFE, ID_EMPRESA, CNPJ_C02, CPF_C02A, XNOME_C03, XFANT_C04, '+
     'XLGR_C06, NRO_C07, XCPL_C08, XBAIRRO_C09, CMUN_C10, XMUN_C11, UF_C12, CEP_C13, CPAIS_C14, XPAIS_C15, ' +
     'FONE_C16, IE_C17, IEST_C18, IM_C19, CNAE_C20, CRT_C21, ISUFEMIT_C22 ' +
     'FROM NFE ' +
     'WHERE ID_NFE = %d', [IdNFe]);

     Result := Format(
     '/*DESTINATÁRIO*/'+
     'SELECT ID_NFE, ID_EMPRESA, '+
     'CNPJ_E02, CPF_E03, IDESTRANGEIRO_E03A, XNOME_E04, XLGR_E06, NRO_E07, XCPL_E08, XBAIRRO_E09, CMUN_E10, XMUN_E11, UF_E12, ' +
     'CEP_E13, CPAIS_E14, XPAIS_E15, FONE_E16, INDIEDEST_E16A, IE_E17, ISUF_E18, IM_E18A, EMAIL_E19, ' +
     'FROM NFE ' +
     'WHERE ID_NFE = %d', [IdNFe]);
   }

End;

Class Function TNFeScript.ScriptInfoAdicional(Const IdNFe: Integer): String;
Begin
   Result := Format(
      'SELECT ID_NFE, FINNFE_B25, TPNF_B11, INFADFISCO_Z02, INFCPL_Z03 FROM NFE WHERE ID_NFE = %d ', [IdNFe]);
End;

Class Function TNFeScript.ScriptInfoContrib(Const IdNFe: Integer): String;
Begin
   Result := Format(
      'SELECT XCAMPO_Z05, XTEXTO_Z06 FROM NFE_INFO_ADIC_CONTR WHERE ID_NFE = %d ', [IdNFe]);
End;

Class Function TNFeScript.ScriptInfoFisco(Const IdNFe: Integer): String;
Begin
   Result := Format(
      'SELECT XCAMPO_Z08, XTEXTO_Z09 FROM NFE_INFO_ADIC_FISCO WHERE ID_NFE = %d ', [IdNFe]);
End;

Class Function TNFeScript.ScriptISIBSCBS(Const IdNFe: Integer): String;
Begin
   Result := Format(
      'SELECT ID_NFE, ID_ITEM, ' +
      { *IS* }
      'CSTIS_UB02, CCLASSTRIBIS_UB03, VBCIS_UB05, PIS_UB06, PISESPEC_UB07, UTRIB_UB09, QTRIB_UB10,VIS_UB11, ' +
      { *IBS/CBS* }
      'CST_UB13, CCLASSTRIB_UB14, INDDOACAO_UB14A, VBC_UB16, ' +
      { *IBS-UF* }
      'PIBSUF_UB18, PDIF_UB22, VDIF_UB23, PDEVTRIB_UB24A,VDEVTRIB_UB25, PREDALIQ_UB27, PALIQEFET_UB28, ' +
      { *IBS-Mun* }
      'PIBSMUN_UB37, PDIF_UB41, VDIF_UB42, PDEVTRIB_UB43A,VDEVTRIB_UB44, PREDALIQ_UB46, PALIQEFET_UB47, ' +
      { *Totais -IBS-UF/Mun* }
      'VIBSUF_UB35, VIBSMUN_UB54, VIBS_UB54A, ' +
      { *CBS* }
      'PCBS_UB56, PDIF_UB60, VDIF_UB61, VDEVTRIB_UB63, PREDALIQ_UB65, PALIQEFET_UB66, TPALCZFMCBS_UB66B, NPROCSUFRAMA_UB66C, PALIQEFETREGCBS_UB66D, VTRIBREGCBS_UB66E, ' +
      { *Total-CBS* }
      'VCBS_UB67, ' +
      { *IBS/CBS* }
      'CSTREG_UB69, CCLASSTRIBREG_UB70, ' +
      { *IBS* }
      'PALIQEFETREGIBSUF_UB71, VTRIBREGIBSUF_UB72, PALIQEFETREGIBSMUN_UB72A, VTRIBREGIBSMUN_UB72B, ' +
      { *CBS* }
      'PALIQEFETREGCBS_UB72C, VTRIBREGCBS_UB72D, ' +
      { *IBS/CBS* }
      'PALIQIBSUF_UB82B, VTRIBIBSUF_UB82C, PALIQIBSMUN_UB82D, VTRIBIBSMUN_UB82E, PALIQCBS_UB82F, VTRIBCBS_UB82G, ' +
      { *MONOFÁSICO* }
      { *IBS-AdRem* }
      'QBCMONO_UB86A, ADREMIBS_UB86B, VIBSMONO_UB86C, QBCMONORETEN_UB87A, ADREMIBSRETEN_UB87B, VIBSMONORETEN_UB87C, VIBSMONORET_UB88A, ' +
      'QBCBIOCOMB_UB89A, VIBSDIFERENCA_UB89B, ' +
      { *IBS-AdValorem* }
      'VBCMONO_UB91A, PALIQMONOUF_UB91B, VIBSMONOUF_UB91C, PALIQMONOMUN_UB91D, VIBSMONOMUN_UB91E, VIBSMONO_UB91F, ' +
      'VBCMONORETEN_UB92A, PALIQMONORETEN_UB92B, VIBSMONORETEN_UB92C, VIBSMONORET_UB93A, ' +
      'QBCBIOCOMB_UB94A, VIBSDIFERENCA_UB94B, ' +
      { *CBS-AdRem* }
      'QBCMONO_UB96A, ADREMCBS_UB96B, VCBSMONO_UB96C, QBCMONORETEN_UB97A, ADREMCBSRETEN_UB97B, VCBSMONORETEN_UB97C, ' +
      'VCBSMONORET_UB98A, QBCBIOCOMB_UB99A, VCBSDIFERENCA_UB99B, ' +
      { *CBS-AdValorem* }
      'VBCMONO_UB101A, PALIQMONOCBS_UB101B, VCBSMONO_UB101C, VBCMONORETEN_UB102A, PALIQMONORETEN_UB102B, VCBSMONORETEN_UB102C, VCBSMONORET_UB103A, ' +
      'QBCBIOCOMB_UB104A, VCBSDIFERENCA_UB104B, ' +
      { *TOTAL IBS/CBS* }
      'VTOTIBSMONOITEM_UB105A, VTOTCBSMONOITEM_UB105B ' +
      'FROM NFE_PROD_IS_IBS_CBS ' +
      'WHERE (ID_NFE = %d) ', [IdNFe]);
End;

Class Function TNFeScript.ScriptPagamentoAntecipado(Const IdNFe: Integer): String;
Begin
   Result := Format(
      ''
      , [IdNFe]);

   // sScript := 'SELECT XCAMPO_Z05, XTEXTO_Z06 FROM NFE_INFO_ADIC_CONTR WHERE ID_NFE = ' + IntToStr(FIdNFe);
End;

Class Function TNFeScript.ScriptCompraGov(Const IdNFe: Integer): String;
Begin
   Result := Format(
      ''
      , [IdNFe]);
   // sScript := 'SELECT XCAMPO_Z08, XTEXTO_Z09 FROM NFE_INFO_ADIC_FISCO WHERE ID_NFE = ' + IntToStr(FIdNFe);
End;

Class Function TNFeScript.ScriptTransporte(Const IdNFe: Integer): String;
Begin
   Result := Format(
      'SELECT NF.MODFRETE_X02, TRA.CNPJ_X04, TRA.CPF_X05, TRA.XNOME_X06, TRA.IE_X07, TRA.XENDER_X08, ' +
      'TRA.XMUN_X09, TRA.UF_X10, ICM.VSERV_X12, ICM.VBCRET_X13, ICM.PICMSRET_X14, ICM.VICMSRET_X15, ICM.CFOP_X16,  ' +
      'ICM.CMUNFG_X17, VEI.PLACA_X19, VEI.UF_X20, VEI.RNTC_X21 FROM NFE NF LEFT JOIN NFE_TRANSPORTADOR TRA ON  ' +
      '(TRA.ID_NFE = NF.ID_NFE)LEFT JOIN NFE_TRANS_ICMS ICM ON(ICM.ID_NFE = NF.ID_NFE)LEFT  ' +
      'JOIN NFE_TRANS_VEICULO VEI ON (VEI.ID_NFE = NF.ID_NFE)WHERE NF.ID_NFE = %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptReboque(Const IdNFe: Integer): String;
Begin
   Result := Format(
      'SELECT * FROM NFE_REBOQUE WHERE ID_NFE =  %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptVolumes(Const IdNFe: Integer): String;
Begin
   Result := Format(
      'SELECT ID_NFE, ID_VOLUME, QVOL_X27, ESP_X28, MARCA_X29, ' +
      'NVOL_X30, PELOL_X31, PELOB_X32 ' +
      'FROM NFE_VOLUME ' +
      'WHERE ID_NFE =  %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptLacres(Const IdNFe, Volume: Integer): String;
Begin
   Result := Format(
      'SELECT NLACRE_X34 FROM NFE_LACRES WHERE ID_NFE = %d AND ID_VOLUME = %d ', [IdNFe, Volume]);
End;

Class Function TNFeScript.ScriptProdutosEImpostos(Const IdNFe: Integer): String;
Begin
   // Blocos LA-combustível,  N-icms, NA-partilha icms, O-ipi, Q-pis, S-cofins ' +
   Result := Format(
      'SELECT ' +
      '/*-- ITENS*/ ' +
      'PRO.ID_ITEM, PRO.ID_SEFAZ, PRO.CPROD_I02, PRO.CEAN_I03, PRO.XPROD_I04, PRO.NCM_I05, ' +
      'PRO.EXTIPI_I06, PRO.CFOP_I08, PRO.UCOM_I09, PRO.QCOM_I10, PRO.VUNCOM_I10A, PRO.VPROD_I11, PRO.CEANTRIB_I12, ' +
      'PRO.UTRIB_I13, PRO.QTRIB_I14, PRO.VUNTRIB_I14A, PRO.VFRETE_I15, PRO.VSEG_I16, PRO.VDESC_I17, PRO.VOUTRO_I17A, ' +
      'PRO.INDTOT_I17B, PRO.XPED_I60, PRO.NITEMPED_I61, PRO.NFCI_I70, PRO.NVE_I05A, ' +
      'PRO.CEST_I05C, PRO.INDESCALA_I05D, PRO.CNPJFAB_I05E, PRO.CBENEF_I05F, ' +

      'INF.INFADPROD_V01, PRO.CHAVEACESSO_VC02, PRO.NITEM_VC03, ' +
      'PRO.VTOTTRIB_M02, ' +

      '/*-- ICMS*/ ' +
      'ICM.ORI_N11, ICM.CST_N12, ICM.CSOSN_N12A, ICM.MODBC_N13, ICM.PREDBC_N14, ICM.VBC_N15, ICM.PICMS_N16, ICM.VICMSOP_N16A, ' +
      'ICM.PDIF_N16B, ICM.VICMSDIF_N16C, ICM.VICMS_N17, ICM.MODBCST_N18, ICM.PMVAST_N19, ICM.PREDBCST_N20, ' +
      'ICM.VBCST_N21, ICM.PICMSST_N22, ICM.VICMSST_N23, ICM.UFST_N24, ICM.PBCOP_N25, ICM.VBCSTRET_N26, ' +
      'ICM.VICMSSTRET_N27, ICM.VICMSDESON_N27A, ICM.MOTDESICMS_N28, ICM.PCREDSN_N29, ICM.VCREDICMSSN_N30, ' +
      'ICM.VBCSTDEST_N31, ICM.VICMSTDEST_N32, ICM.VBCUFDEST_NA03, ICM.PFCPUFDEST_NA05, ICM.PICMSUFDEST_NA07, ICM.PICMSINTER_NA09, ' +
      'ICM.PICMSINTERPART_NA11, ICM.VFCPUFDEST_NA13, ICM.VICMSUFDEST_NA15, ICM.VICMSUFREMET_NA17, ' +
      'ICM.VBCFCP_N17A, ICM.PFCP_N17B, ICM.VFCP_N17C, ICM.VBCFCPST_N23A, ICM.PFCPST_N23B, ICM.VFCPST_N23D, ICM.PST_N26A, ' +
      'ICM.VBCFCPSTRET_N27A, ICM.PFCPSTRET_N27B, ICM.VFCPSTRET_N27D, ICM.VBCFCPUFDEST_NA04, ' +
      'ICM.QBCMONO_N37A, ICM.ADREMICMS_N38, ICM.VICMSMONO_N39, ICM.QBCMONORETEN_N39A, ICM.ADREMICMSRETEN_N40, ICM.VICMSMONORETEN_N41, ICM.VICMSMONOOP_N41A, ' +
      'ICM.PDIF_N42, ICM.VICMSMONODIF_N43, ICM.QBCMONORET_N43A, ICM.ADREMICMSRET_N44, ICM.VICMSMONORET_N45, ICM.PREDADREM_N47, ICM.MOTREDADREM_N48, ' +

      '/*-- PIS*/ ' +
      'PIS.CST_Q06, PIS.VBC_Q07, PIS.PPIS_Q08, PIS.VPIS_Q09, PIS.QBCPROD_Q10, PIS.VALIQPROD_Q11, ' +

      '/*--COFINS*/ ' +
      'COF.CST_S06, COF.VBC_S07, COF.PCOFINS_S08, COF.QBCPROD_S09, COF.VALIQPROD_S10, COF.VCOFINS_S11, ' +

      '/*-- ISS*/ ' +
      'ISS.VBC_U02, ISS.VALIQ_U03, ISS.VISSQN_U04, ISS.CNUMFG_U05, ISS.CLISTSERV_U06, ' +
      'ISS.VDEDUCAO_U07, ISS.VOUTRO_U08, ISS.VDESCINCOND_U09, ISS.VDESCOND_U10, ISS.VISSRET_U11, ISS.INDISS_U12, ' +
      'ISS.CSERVICO_U13, ISS.CMUN_U14, ISS.CPAIS_U15, ISS.NPROCESSO_U16, ISS.INDINCENTIVO_U17, ' +

      '/*--COMBUSÍVEIS*/ ' +
      'COMB.CPRODANP_LA02, COMB.DESCANP_LA03, COMB.CODIF_LA04, COMB.QTEMP_LA05, COMB.UFCONS_LA06, COMB.PMIXGN_LA03, ' +
      'COMB.PGLP_LA03A, COMB.PGNN_LA03B, COMB.PGNI_LA03C, COMB.VPART_LA03D, ' +
      'COMB.QBCPROD_LA08, COMB.VALIQPROD_LA09, COMB.VCIDE_LA10, ' +
      'COMB.NBICO_LA12, COMB.NBOMBA_LA13, COMB.NTANQUE_LA14, COMB.VENCINI_LA15, COMB.VENCFIN_LA16, COMB.PBIO_LA17, ' +

      '/*-- IPI*/ ' +
      'IPI.CNPJPROD_O03, IPI.CSELO_O04, IPI.QSELO_O05, IPI.CENQ_O06, IPI.CST_O09, IPI.VBC_O10, IPI.QUNID_O11, ' +
      'IPI.VUNID_O12, IPI.PIPI_O13, IPI.VIPI_O14, IPI.CLENQ_O02, IPI.PDEVOL_UA02, IPI.VIPIDEVOL_UA04 ' +
      'FROM NFE_PROD PRO ' +
      'LEFT JOIN NFE_PROD_INFADIC INF ON (INF.ID_NFE = PRO.ID_NFE AND INF.ID_ITEM = PRO.ID_ITEM) ' +
      'LEFT JOIN NFE_PROD_ICMS ICM ON(ICM.ID_NFE = PRO.ID_NFE AND ICM.ID_ITEM = PRO.ID_ITEM) ' +
      'LEFT JOIN NFE_PROD_PIS PIS ON(PIS.ID_NFE = PRO.ID_NFE AND PIS.ID_ITEM = PRO.ID_ITEM) ' +
      'LEFT JOIN NFE_PROD_COFINS COF ON(COF.ID_NFE = PRO.ID_NFE AND COF.ID_ITEM = PRO.ID_ITEM) ' +
      'LEFT JOIN NFE_PROD_ISSQN ISS ON(ISS.ID_NFE = PRO.ID_NFE AND ISS.ID_ITEM = PRO.ID_ITEM) ' +
      'LEFT JOIN NFE_PROD_COMB COMB ON(COMB.ID_NFE = PRO.ID_NFE AND COMB.ID_ITEM = PRO.ID_ITEM) ' +
      'LEFT JOIN NFE_PROD_IPI IPI ON(IPI.ID_NFE = PRO.ID_NFE AND IPI.ID_ITEM = PRO.ID_ITEM) ' +
      'WHERE PRO.ID_NFE =  %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptReferenciadas(Const IdNFe: Integer): String;
Begin
   // Result := Format(
   // '-- SQL PARA O BLOCO B02-REFERENCIADOS '+
   // 'BLOCO B02 ' +
   // 'SELECT ID_NFE, ID_NFE_RF, REFNFE_BA02, REFCTE_BA19, REFDFEANT_BB05, NITEM_VC03 ' +
   // 'FROM NFE_REF_NFE ' +
   // 'WHERE ID_NFE = %d', [IdNFe]);

   // BLOCO VC - REFERENCIADOS ' +
   Result := Format(
      'SELECT ID_NFE, ID_NFE_RF, REFNFE_BA02, REFCTE_BA19, REFDFEANT_BB05, NITEM_VC03 ' +
      'FROM NFE_REF_NFE ' +
      'WHERE ID_NFE = %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptRetiradas(Const IdNFe: Integer): String;
Begin
   // BLOCO F - RETIRADA ' +
   Result := Format(
      'SELECT ID_NFE, CNPJ_F02, CPF_F02A, XLGR_F03, NRO_F04, XCPL_F05, XBAIRRO_F06, CMUN_F07, XMUN_F08, UF_F09 ' +
      'FROM NFE_LOCAL_RETIRADA ' +
      'WHERE ID_NFE = %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptTotais(Const IdNFe: Integer): String;
Begin
   // BLOCO W - TOTAIS ' +
   Result := Format(
      'SELECT NF.VBC_W03, NF.VICMS_W04, NF.VICMSDESON_W04A, NF.VBCST_W05, NF.VST_W06, NF.VPROD_W07, ' +
      'NF.VFRETE_W08, NF.VSEG_W09, NF.VDESC_W10, NF.VII_W11, NF.VIPI_W12, NF.VPIS_W13, NF.VCOFINS_W14, ' +
      'NF.VOUTRO_W15, NF.VNF_W16, NF.VTOTTRIB_W16A, NF.VFCPUFDEST_W04C, NF.VICMSUFDEST_W04E, NF.VICMSUFREMET_W04G, ' +
      'NF.VFCP_W04H, NF.VFCPST_W06A, NF.VFCPSTRET_W06B, NF.VIPIDEVOL_W12A, ' +
      'NF.QBCMONO_W06B1, NF.VICMSMONO_W06C, NF.QBCMONORETEN_W06C1, NF.VICMSMONORETEN_W06D, NF.QBCMONORET_W06D1, NF.VICMSMONORET_W06E, ' +

      (* MOVIDO PARA ScriptTotaisISIBSCBS
        'NF.VIS_W33, NF.VBCIBSCBS_W35, NF.VDIF_W38, NF.VDEVTRIB_W39, ' +
        'NF.VIBSUF_W41, NF.VDIF_W43, NF.VDEVTRIB_W44, NF.VIBSMUN_W46, ' +
        'NF.VIBS_W47, NF.VCREDPRES_W48, NF.VCREDPRESCONDSUS_W49, NF.VDIF_W53, NF.VDEVTRIB_W54, NF.VCBS_W56, NF.VCREDPRES_W56A, ' +
        'NF.VIBSMONO_W58, NF.VCBSMONO_W59, NF.VIBSMONORETEN_W59A, NF.VCBSMONORETEN_W59B, NF.VIBSMONORET_W59C, NF.VCBSMONORET_W59D, ' +
        'NF.VIBSESTCRED_W59F, NF.VCBSESTCRED_W59G, NF.VNFTOT_W60, ' +
      *)

      'ISS.VSERV_W18, ISS.VBC_W19, ISS.VISS_W20, ISS.VPIS_W21, ISS.VCOFINS_W22, ISS.DCOMPET_W22A, ISS.VDEDUCAO_W22B, ' +
      'ISS.VOUTRO_W22C, ISS.VDESCINCOND_W22D, ISS.VDESCCOND_W22E, ISS.VISSRET_W22F, ISS.CREGTRIB_W22G, ' +

      'RET.VRETPIS_W24, RET.VRETCOFINS_W25, ' +
      'RET.VRETCSLL_W26, RET.VBCIRRF_W27, RET.VIRRF_W28, RET.VBCRETPREV_W29, RET.VRETPREV_W30 ' +

      'FROM NFE NF ' +
      'LEFT JOIN NFE_TOTAL_ISS ISS ON (ISS.ID_NFE = NF.ID_NFE) ' +
      'LEFT JOIN NFE_TOTAL_RETENCAO RET ON(RET.ID_NFE = NF.ID_NFE) ' +
      'WHERE NF.ID_NFE =  %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptTotaisISIBSCBS(Const IdNFe: Integer): String;
Begin
   { IMPLEMENTAR->vCredPresCondSus_W56B }
   Result := Format(
      'SELECT VIS_W33, VBCIBSCBS_W35, VDIF_W38, VDEVTRIB_W39, VIBSUF_W41, VDIF_W43, VDEVTRIB_W44, VIBSMUN_W46, ' +
      'VIBS_W47, VCREDPRES_W48, VCREDPRESCONDSUS_W49, VDIF_W53, VDEVTRIB_W54, VCBS_W56, VCREDPRES_W56A, VIBSMONO_W58, ' +
      'VCBSMONO_W59, VIBSMONORETEN_W59A, VCBSMONORETEN_W59B, VIBSMONORET_W59C, VCBSMONORET_W59D, VIBSESTCRED_W59F, ' +
      'VCBSESTCRED_W59G, VNFTOT_W60 ' +
      'FROM NFE ' +
      'WHERE ID_NFE = %d', [IdNFe]);
End;

Class Function TNFeScript.ScriptTransportador(Const IdNFe: Integer): String;
Begin
   // BLOCOS X, X22, X26 - TRANSPORTADOR, VEICULO, ICMS ' +
   Result := Format(
      'SELECT NF.MODFRETE_X02, TRA.CNPJ_X04, TRA.CPF_X05, TRA.XNOME_X06, TRA.IE_X07, TRA.XENDER_X08, ' +
      'TRA.XMUN_X09, TRA.UF_X10, ICM.VSERV_X12, ICM.VBCRET_X13, ICM.PICMSRET_X14, ICM.VICMSRET_X15, ICM.CFOP_X16, ' +
      'ICM.CMUNFG_X17, VEI.PLACA_X19, VEI.UF_X20, VEI.RNTC_X21 ' +
      'FROM NFE NF ' +
      'LEFT JOIN NFE_TRANSPORTADOR TRA ON (TRA.ID_NFE = NF.ID_NFE) ' +
      'LEFT JOIN NFE_TRANS_ICMS ICM ON(ICM.ID_NFE = NF.ID_NFE) ' +
      'LEFT JOIN NFE_TRANS_VEICULO VEI ON (VEI.ID_NFE = NF.ID_NFE) ' +
      'WHERE NF.ID_NFE =  %d', [IdNFe]);
End;

End.
